### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by asonnino** [lsonnino/code-metallifood#1]
- Add picture of the system
- Add circuit diagram (i.e., diagram of Arduino and its connections)
- The Arduino has an EEPROM memory (non volatile): store detections on that memory (example [here](https://www.arduino.cc/en/Tutorial/EEPROMWrite)) -- protect EEPROM with preprocessor macros (only 10k write on EEPROM)
- Use pre processor macro to define pin number etc
- be careful with the resistor you use before the LEDs (Arduino outputs 5V -- too much for LEDs)
- Print debugging with preprocessor macros 
- Use different _branches_ in GitHub for dev and stable version (and not different folders); i.e., stable version on Master branch

**Comment by lsonnino** [comment]
Thank you for your comment, we will take account of your suggestions and let you know about the future updates

**Comment by per1234** [comment]
>Use different branches in GitHub for dev and stable version (and not different folders); i.e., stable version on Master branch

I'm glad to see this change made. In addition, I'd suggest that rather than versioning via the folder/file name you should use [GitHub releases](https://help.github.com/articles/creating-releases/)/[Git tags](https://git-scm.com/docs/git-tag) for versioning. Otherwise when you change the folder and/or file name it breaks the version history for the file. GitHub makes it very easy to view and download the contents of the repository at any tag.

**Comment by lsonnino** [comment]
Thanks a lot for your advice, we will take a look as soon as we get the version 2.0 working.
